### ISSUE TITLE
Emacs is designated mildly narcotic and moderately funny it's neither of these things.

### ISSUE THREAD

**Issue by michaelmrose** [flathub/org.gnu.emacs#41]
Please see

https://github.com/flathub/org.gnu.emacs/blob/master/appdata-content-rating.patch

These bizarrely conceived ratings result in Elementary OS throwing up a warning to those installing Emacs. See

 https://www.reddit.com/r/elementaryos/comments/p3u98f/this_made_me_laugh_x_rated_emacs/?sort=new

None of those entries make sense. Even social chat which would seem to apply to an application with a bad web browser and a decent IRC client doesn't make sense on a spectrum from mild to intense.

Edit:removed nonconstructive text better ommitted

**Comment by muep** [comment]
Hi Michael,

If I recall correctly, I would have been happy to leave out the content rating, but it was added because Flathub requires it to be present in the application metadata. However, feel free to suggest improvements in the content_rating part.

The issue title kind of suggests two changes.

At least the [generator](https://hughsie.github.io/oars/generate.html) describes the 'mild' category for narcotic such, that simply referencing alcohol or drugs is sufficient for receiving the mild rating. In my view, Emacs clearly includes such references, even though they are not exactly up-front when you use it.

For humor, the ratings are described as:
- mild: slapstick humor
- moderate: vulgar or bathroom humor
- intense: mature or sexual humor

Please note that the rating has nothing to do if the jokes are actually funny.

I do not remember what exact content in Emacs made me think that it should match the moderate description. This may well be an oversight as well, because it was not like I wanted to spend a lot of time on the classification when it was originally done. I will try to find time to look at this, and if can't find actual examples, I think it would be reasonable to switch to a milder humor rating.

**Comment by michaelmrose** [comment]
Thank you for taking the time to address the matter. Sorry if my initial tone was harsh. I meant the title itself as a bit of humor. Lets go over the ratings themselves.

<content_attribute id="drugs-alcohol">mild</content_attribute>
<content_attribute id="drugs-narcotics">mild</content_attribute>
<content_attribute id="drugs-tobacco">mild</content_attribute>

Mild would be references to illicit drugs, alcohol, or tabacco. None would be more appropriate.

<content_attribute id="sex-themes">mild</content_attribute>

I would guess you could if you were so inclined decide that the fact that it contains doctor a goof chatter bot that asks questions can ask the user questions and can pretend to give responses can ask the question "hows your sex life" you could put mild although this is pretty silly. I spent several minutes trying to get doctor to say something lewd and it required using the keyword sex to get it to ask such questions as "are you afraid of sex" and "what is your sexual history". As far as lasciviousness this is right up there with being 5 and realizing that the dictionary contains references to words that could be taken to be dirty in some contexts.

<content_attribute id="language-profanity">mild</content_attribute>

The people that created the standard are incompetent and don't understand what words mean.

In brief a definition of profanity: blasphemous or obscene language.

Their example of mild profanity is dufus. Dufus is actually first off actually not a word. Doofus is not profane. I could not find any profanity that users could encounter not even the word doofus or even yet dufus. I could find in the source code not in the user interface references to dirty words such that for example doctor could respond with such gems as "get your mind out of the gutter" or "watch your tongue". It is quite normal for a program to contain a bad word list used to recognize profanity in text entered by the user and such bad word files don't normally make the program itself profane. In fact examination of the source code in place of the interface it presents to the user is pretty much nonsense in that respect.

<content_attribute id="language-humor">moderate</content_attribute>

Where?

<content_attribute id="social-chat">intense</content_attribute>
<content_attribute id="social-contacts">intense</content_attribute>

I guess anything that has social chat logically can allow you to type your email address into the chat so the second is a bit redundant but as you will.

**Comment by nanonyme** [comment]
To be honest, I would try just adding content rating element, leaving it empty and seeing if it goes through. This is what Firefox currently has.

**Comment by muep** [comment]
Sorry for taking such a long time to respond to this.

I don't think shipping simply an empty rating aligns well with the intent of whoever chose to make it mandatory on Flathub. If there is documentation that it 

The current `social-chat` seem to match what other chat clients are using. Examples:
-  [Discord](https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.appdata.xml#L82)
- [Quassel](https://github.com/flathub/org.quassel_irc.QuasselClient/blob/master/org.quassel_irc.QuasselClient.appdata.xml#L24)
- [Hexchat](https://github.com/hexchat/hexchat/blob/master/data/misc/io.github.Hexchat.appdata.xml.in#L118) (upstream)

OTOH I think the other bits leave more room for interpretation, so I suppose we can just clear those out and revisit the topic in case someone brings further arguments towards lowering to bar for receiving a non-empty rating on some area.
